#!/bin/bash
# Переброс тем и конфигов
sudo cp Hacked-White /usr/share/icons
sudo cp Numix /usr/share/icons
sudo cp Nordic-darker /usr/share/themes
cp sublime-text ~/.config
cp input-remapper ~/.config
cd 

# Установка всего первостепенного и не очень
sudo pacman -Syu conky curl discord git neofetch steam  torbrowser-launcher zsh

# Oh-my-zsh
curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
echo "source ${(q-)PWD}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ${ZDOTDIR:-$HOME}/.zshrc

# Yay
git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si && cd
yay -S librewolf input-remapper-git

# Sublime text
curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg
echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | sudo tee -a /etc/pacman.conf
sudo pacman -Syu sublime-text

# Удалить репы sublime /etc/pacman.conf
for (( i=1; i <= 2; i++ ))
do
sudo sed -i '$d' /etc/pacman.conf
done

# Настройки Gnome
gnome-tweaks &
